name: Crous Notifier

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run notifier
        env:
          MY_TELEGRAM_ID: ${{ secrets.MY_TELEGRAM_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          MSE_EMAIL: ${{ secrets.MSE_EMAIL }}
          MSE_PASSWORD: ${{ secrets.MSE_PASSWORD }}
        run: poetry run python main.py
